  node8:
    build:
      context: ./docker/container/node/node8/
      dockerfile: Dockerfile
    container_name: node8
    dns: "${DNS_IP-8.8.8.8}"
    expose:
      - 8080
    ports:
      - "${NODE8_BRIDGED_PORT-9008}:8080"
    image: flower7c3/node:8
    networks:
      webserver:
    restart: 'no'
    tty: true
    volumes:
      - type: bind
        source: "${VOLUME_SSH_LOCAL_PATH}"
        target: "${VOLUME_SSH_TARGET}"
      - type: bind
        source: "${VOLUME_BASH_HISTORY_LOCAL_PATH}"
        target: "${VOLUME_BASH_HISTORY_TARGET}"
      - type: bind
        source: "${VOLUME_TOOLS_LOCAL_PATH}"
        target: "${VOLUME_TOOLS_TARGET}"
      - type: bind
        source: "${VOLUME_PROJECTS_LOCAL_PATH}"
        target: "${VOLUME_PROJECTS_TARGET}"
        volume:
          cached: true
      - type: bind
        source: "${VOLUME_DOMAINS_LOCAL_PATH}"
        target: "${VOLUME_DOMAINS_TARGET}"
        volume:
          cached: true
