  mysql55:
    build:
      context: ./docker/container/mysql/mysql55/
      dockerfile: Dockerfile
    container_name: mysql55
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL55_ROOT_PASSWORD}"
    expose:
      - 3306
    image: flower7c3/mysql:5.5
    networks:
      ${NETWORK_NAME}:
        # ipv4_address: ${MYSQL55_DOCKER_NETWORK_IP}
    ports:
      - "${MYSQL_BRIDGED_PORT}:3306"
      - "${MYSQL55_BRIDGED_PORT}:3306"
    restart: always
    volumes:
      - type: bind
        source: "${VOLUME_SSH_SOURCE}"
        target: "${VOLUME_SSH_TARGET}"
      - type: bind
        source: "${VOLUME_TOOLS_LOCAL_PATH}"
        target: "${VOLUME_TOOLS_TARGET}"
      - type: "${VOLUME_PROJECTS_TYPE}"
        source: "${VOLUME_PROJECTS_SOURCE}"
        target: "${VOLUME_PROJECTS_TARGET}"
        ${VOLUME_PROJECTS_OPTIONS}
      - type: "${VOLUME_DOMAINS_TYPE}"
        source: "${VOLUME_DOMAINS_SOURCE}"
        target: "${VOLUME_DOMAINS_TARGET}"
        ${VOLUME_DOMAINS_OPTIONS}
      - type: "${VOLUME_MYSQL55_TYPE}"
        source: "${VOLUME_MYSQL55_LOCAL_PATH}"
        target: "${VOLUME_MYSQL55_TARGET}"
        ${VOLUME_MYSQL55_OPTIONS}
