  mysql55:
    build:
      context: ./docker/container/mysql/mysql55/
      dockerfile: Dockerfile
    container_name: mysql55
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL55_ROOT_PASSWORD}"
    expose:
      - 3306
    image: flower7c3/mysql:5.5
    networks:
      webserver:
        ipv4_address: ${MYSQL55_DOCKER_NETWORK_IP}
    ports:
      - "${MYSQL_BRIDGED_PORT}:3306"
      - "${MYSQL55_BRIDGED_PORT}:3306"
    restart: always
    volumes:
      - "${VOLUME_SSH}:/root/.ssh/"
      - "projects-sync:/var/www/projects/:nocopy"
      - "domains-sync:/var/www/domains/:nocopy"
      # - "${VOLUME_PROJECTS}:/var/www/projects/"
      # - "${VOLUME_DOMAINS}:/var/www/domains/"
      - "mysql55-sync:/var/lib/mysql/:nocopy"
      # - "${VOLUME_DATABASES}mysql/mysql55/data/:/var/lib/mysql"
      - "${VOLUME_TOOLS}:/var/www/bin/"
