  nginx-proxy:
    container_name: proxy
    environment:
      DEFAULT_HOST: "${PROXY_DEFAULT_HOST}"
    expose:
      - 80
    image: jwilder/nginx-proxy
    networks:
      webserver:
        # ipv4_address: ${PROXY_DOCKER_NETWORK_IP}
    ports:
      - "${PROXY_HTTP0_BRIDGED_PORT-80}:80"
      - "${PROXY_HTTPS_BRIDGED_PORT-443}:443"
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - type: bind
        source: "${VOLUME_SSH_LOCAL_PATH}"
        target: "${VOLUME_SSH_TARGET}"
      - type: bind
        source: "${VOLUME_BASH_HISTORY_LOCAL_PATH}"
        target: "${VOLUME_BASH_HISTORY_TARGET}"
      - type: bind
        source: "${VOLUME_TOOLS_LOCAL_PATH}"
        target: "${VOLUME_TOOLS_TARGET}"
      - type: bind
        source: "${VOLUME_PROJECTS_LOCAL_PATH}"
        target: "${VOLUME_PROJECTS_TARGET}"
        volume:
          cached: true
      - type: bind
        source: "${VOLUME_DOMAINS_LOCAL_PATH}"
        target: "${VOLUME_DOMAINS_TARGET}"
        volume:
          cached: true

