  nginx-proxy:
    container_name: proxy
    environment:
      DEFAULT_HOST: "${PROXY_DEFAULT_HOST}"
    expose:
      - 80
    image: jwilder/nginx-proxy
    networks:
      webserver:
        ipv4_address: ${PROXY_DOCKER_NETWORK_IP}
    ports:
      - "${PROXY_HTTP0_BRIDGED_PORT}:80"
      - "${PROXY_HTTPS_BRIDGED_PORT}:443"
    restart: always
    volumes:
      - "${VOLUME_SSH}:/root/.ssh/"
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - "projects-sync:/var/www/projects/:nocopy"
      - "domains-sync:/var/www/domains/:nocopy"
      # - "${VOLUME_PROJECTS}:/var/www/projects/"
      # - "${VOLUME_DOMAINS}:/var/www/domains/"
      - "${VOLUME_TOOLS}:/var/www/bin/"
