  nginx-proxy:
    container_name: proxy
    environment:
      DEFAULT_HOST: "${PROXY_DEFAULT_HOST}"
    expose:
      - 80
    image: jwilder/nginx-proxy
    networks:
      ${NETWORK_NAME}:
        # ipv4_address: ${PROXY_DOCKER_NETWORK_IP}
    ports:
      - "${PROXY_HTTP0_BRIDGED_PORT}:80"
      - "${PROXY_HTTPS_BRIDGED_PORT}:443"
    restart: always
    volumes:
      - type: bind
        source: "${VOLUME_SSH_SOURCE}"
        target: "${VOLUME_SSH_TARGET}"
      - type: bind
        source: "${VOLUME_TOOLS_LOCAL_PATH}"
        target: "${VOLUME_TOOLS_TARGET}"
      - type: "${VOLUME_PROJECTS_TYPE}"
        source: "${VOLUME_PROJECTS_SOURCE}"
        target: "${VOLUME_PROJECTS_TARGET}"
        ${VOLUME_PROJECTS_OPTIONS}
      - type: "${VOLUME_DOMAINS_TYPE}"
        source: "${VOLUME_DOMAINS_SOURCE}"
        target: "${VOLUME_DOMAINS_TARGET}"
        ${VOLUME_DOMAINS_OPTIONS}
      - /var/run/docker.sock:/tmp/docker.sock:ro

