#!/usr/bin/env bash

MONGO3_ROOT_USERNAME=root
MONGO3_ROOT_PASSWORD=rootpasswd
MONGO3_DOCKER_NETWORK_IP=192.168.33.183
MONGO3_BRIDGED_PORT=27017

VOLUME_MONGO3_LOCAL_PATH="${VOLUME_DATABASES_LOCAL_PATH}mongo/mongo3/data/"
VOLUME_MONGO3_TARGET="/data/db/"
if [[ "$DOCKER_SYNC_STRATEGY" == "" ]]; then
    VOLUME_MONGO3_TYPE="bind"
    VOLUME_MONGO3_SOURCE="${VOLUME_MONGO3_LOCAL_PATH}"
    VOLUME_MONGO3_OPTIONS=""
    VOLUME_MONGO3_DEFINITION=""
else
    VOLUME_MONGO3_TYPE="volume"
    VOLUME_MONGO3_SOURCE="mongo3-sync"
    VOLUME_MONGO3_OPTIONS="volume:
              nocopy: true"
    VOLUME_MONGO3_DEFINITION="${VOLUME_MONGO3_SOURCE}:
        external: true"
fi
