  mongo3:
    build:
      context: ./docker/container/mongo/mongo3/
      dockerfile: Dockerfile
    container_name: mongo3
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: "${MONGO3_ROOT_USERNAME-root}"
      # MONGO_INITDB_ROOT_PASSWORD: "${MONGO3_ROOT_PASSWORD-rootpasswd}"
    expose:
      - "3306"
    image: flower7c3/mongo:3
    networks:
      webserver:
        # ipv4_address: ${MONGO3_DOCKER_NETWORK_IP}
    ports:
      - "${MONGO3_BRIDGED_PORT-27017}:27017"
    restart: always
    volumes:
      - type: bind
        source: "${VOLUME_SSH_LOCAL_PATH}"
        target: "${VOLUME_SSH_TARGET}"
      - type: bind
        source: "${VOLUME_BASH_HISTORY_LOCAL_PATH}"
        target: "${VOLUME_BASH_HISTORY_TARGET}"
      - type: bind
        source: "${VOLUME_TOOLS_LOCAL_PATH}"
        target: "${VOLUME_TOOLS_TARGET}"
      - type: bind
        source: "${VOLUME_PROJECTS_LOCAL_PATH}"
        target: "${VOLUME_PROJECTS_TARGET}"
        volume:
          cached: true
      - type: bind
        source: "${VOLUME_DOMAINS_LOCAL_PATH}"
        target: "${VOLUME_DOMAINS_TARGET}"
        volume:
          cached: true
      - type: bind
        source: "${VOLUME_MONGO3_LOCAL_PATH}"
        target: "/data/db/"
        volume:
          cached: true
