  mongo3:
    build:
      context: ./docker/container/mongo/mongo3/
      dockerfile: Dockerfile
    container_name: mongo3
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: "${MONGO3_ROOT_USERNAME}"
      # MONGO_INITDB_ROOT_PASSWORD: "${MONGO3_ROOT_PASSWORD}"
    expose:
      - "3306"
    image: flower7c3/mongo:3
    networks:
      ${NETWORK_NAME}:
        # ipv4_address: ${MONGO3_DOCKER_NETWORK_IP}
    ports:
      - "${MONGO3_BRIDGED_PORT}:27017"
    restart: always
    volumes:
      - type: bind
        source: "${VOLUME_SSH_SOURCE}"
        target: "${VOLUME_SSH_TARGET}"
      - type: bind
        source: "${VOLUME_TOOLS_LOCAL_PATH}"
        target: "${VOLUME_TOOLS_TARGET}"
      - type: "${VOLUME_PROJECTS_TYPE}"
        source: "${VOLUME_PROJECTS_SOURCE}"
        target: "${VOLUME_PROJECTS_TARGET}"
        ${VOLUME_PROJECTS_OPTIONS}
      - type: "${VOLUME_DOMAINS_TYPE}"
        source: "${VOLUME_DOMAINS_SOURCE}"
        target: "${VOLUME_DOMAINS_TARGET}"
        ${VOLUME_DOMAINS_OPTIONS}
      - type: "${VOLUME_MONGO3_TYPE}"
        source: "${VOLUME_MONGO3_LOCAL_PATH}"
        target: "${VOLUME_MONGO3_TARGET}"
        ${VOLUME_MONGO3_OPTIONS}
