
  mongo3:
    build:
      context: ./docker/container/mongo/mongo3/
      dockerfile: Dockerfile
    container_name: mongo3
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: "${MONGO3_ROOT_USERNAME}"
      # MONGO_INITDB_ROOT_PASSWORD: "${MONGO3_ROOT_PASSWORD}"
    expose:
      - "3306"
    image: flower7c3/mongo:3
    networks:
      webserver:
        ipv4_address: ${MONGO3_DOCKER_NETWORK_IP}
    ports:
      - "${MONGO3_BRIDGED_PORT}:27017"
    restart: always
    volumes:
      - "${VOLUME_PROJECTS}:/var/www/projects/"
      - "${VOLUME_DOMAINS}:/var/www/domains/"
      - "${VOLUME_TOOLS}:/var/www/bin/"
      - "${VOLUME_DATABASE}mongo/mongo3/data/:/data/db"

