version: '2'

services:

  debian-jessie:
    build:
      context: ./docker/container/debian/debian-jessie/
      dockerfile: Dockerfile
    container_name: debian
    image: flower7c3/debian:jessie
    restart: 'no'
    tty: true

  nginx-proxy:
    container_name: proxy
    environment:
      DEFAULT_HOST: "${PROXY_DEFAULT_HOST}"
    image: jwilder/nginx-proxy
    networks:
      webserver:
        ipv4_address: ${PROXY_DOCKER_NETWORK_IP}
    ports:
      - "${PROXY_HTTP0_BRIDGED_PORT}:80"
#      - "${PROXY_HTTP1_BRIDGED_PORT}:81"
      - "${PROXY_HTTPS_BRIDGED_PORT}:443"
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - "~/.ssh/:/root/.ssh/"
      - "${VOLUME_PROJECTS}:/var/www/projects/"
      - "${VOLUME_DOMAINS}:/var/www/domains/"
      - "${VOLUME_TOOLS}:/var/www/tools/"

  mysql55:
    build:
      context: ./docker/container/mysql/mysql55/
      dockerfile: Dockerfile
    container_name: mysql55
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL55_ROOT_PASSWORD}"
      PHP55_IP: ${PHP55_DOCKER_NETWORK_IP}
      PHP56_IP: ${PHP56_DOCKER_NETWORK_IP}
      PHP70_IP: ${PHP70_DOCKER_NETWORK_IP}
      #PHP71_IP: ${PHP71_DOCKER_NETWORK_IP}
    expose:
      - "3306"
    image: flower7c3/mysql:5.5
    networks:
      webserver:
        ipv4_address: ${MYSQL55_DOCKER_NETWORK_IP}
    ports:
      - "${MYSQL55_BRIDGED_PORT}:3306"
    restart: always
    volumes:
      - "${VOLUME_PROJECTS}:/var/www/projects/"
      - "${VOLUME_DOMAINS}:/var/www/domains/"
      - "${VOLUME_TOOLS}:/var/www/tools/"
      - "${VOLUME_ROOT}mysql/mysql55/data/:/var/lib/mysql"

  mysql56:
    build:
      context: ./docker/container/mysql/mysql56/
      dockerfile: Dockerfile
    container_name: mysql56
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL56_ROOT_PASSWORD}"
      PHP55_IP: ${PHP55_DOCKER_NETWORK_IP}
      PHP56_IP: ${PHP56_DOCKER_NETWORK_IP}
      PHP70_IP: ${PHP70_DOCKER_NETWORK_IP}
      #PHP71_IP: ${PHP71_DOCKER_NETWORK_IP}
    expose:
      - "3306"
    image: flower7c3/mysql:5.6
    networks:
      webserver:
        ipv4_address: ${MYSQL56_DOCKER_NETWORK_IP}
    ports:
      - "${MYSQL56_BRIDGED_PORT}:3306"
    restart: always
    volumes:
      - "${VOLUME_PROJECTS}:/var/www/projects/"
      - "${VOLUME_DOMAINS}:/var/www/domains/"
      - "${VOLUME_TOOLS}:/var/www/tools/"
      - "${VOLUME_ROOT}mysql/mysql56/data/:/var/lib/mysql"

  elastic1:
    container_name: elastic1
    dns: "${DNS_IP}"
    image: elasticsearch:1
    networks:
      webserver:
        ipv4_address: ${ELASTICSEARCH1_DOCKER_NETWORK_IP}
    ports:
      - "${ELASTICSEARCH1_BRIDGED_PORT}:9200"
    restart: 'no'
    tty: true
    volumes:
      - "~/.ssh/:/root/.ssh/"
      - "${VOLUME_ROOT}esdata/:/usr/share/elasticsearch/data/"
      - "${VOLUME_PROJECTS}:/var/www/projects/"
      - "${VOLUME_DOMAINS}:/var/www/domains/"
      - "${VOLUME_TOOLS}:/var/www/tools/"

  php55:
    build:
      context: ./docker/container/php/php55/
      dockerfile: Dockerfile
    container_name: php55
    dns: "${DNS_IP}"
    environment:
      VIRTUAL_HOST: "${PHP55_VIRTUAL_HOSTS}"
      XDEBUG_CONFIG: "remote_host=${HOST_IPS[1]}"
    image: flower7c3/php:5.5-apache
    links:
      - mysql55
      - mysql56
      - elastic1
    networks:
      webserver:
        ipv4_address: ${PHP55_DOCKER_NETWORK_IP}
    restart: always
    volumes:
      - "~/.ssh/:/root/.ssh/"
      - "${VOLUME_WWW_INDEX}:/var/www/html/"
      - "${VOLUME_PROJECTS}:/var/www/projects/"
      - "${VOLUME_DOMAINS}:/var/www/domains/"
      - "${VOLUME_TOOLS}:/var/www/tools/"

  php56:
    build:
      context: ./docker/container/php/php56/
      dockerfile: Dockerfile
    container_name: php56
    environment:
      VIRTUAL_HOST: "${PHP56_VIRTUAL_HOSTS}"
      XDEBUG_CONFIG: "remote_host=${HOST_IPS[1]}"
    dns: "${DNS_IP}"
    image: flower7c3/php:5.6-apache
    links:
      - mysql55
      - mysql56
      - elastic1
    networks:
      webserver:
        ipv4_address: ${PHP56_DOCKER_NETWORK_IP}
    restart: always
    volumes:
      - "~/.ssh/:/root/.ssh/"
      - "${VOLUME_WWW_INDEX}:/var/www/html/"
      - "${VOLUME_PROJECTS}:/var/www/projects/"
      - "${VOLUME_DOMAINS}:/var/www/domains/"
      - "${VOLUME_TOOLS}:/var/www/tools/"

  php70:
    build:
      context: ./docker/container/php/php70/
      dockerfile: Dockerfile
    container_name: php70
    dns: "${DNS_IP}"
    environment:
      VIRTUAL_HOST: "${PHP70_VIRTUAL_HOSTS}"
      XDEBUG_CONFIG: "remote_host=${HOST_IPS[1]}"
    image: flower7c3/php:7.0-apache
    links:
      - mysql55
      - mysql56
      - elastic1
    networks:
      webserver:
        ipv4_address: ${PHP70_DOCKER_NETWORK_IP}
    restart: always
    volumes:
      - "~/.ssh/:/root/.ssh/"
      - "${VOLUME_WWW_INDEX}:/var/www/html/"
      - "${VOLUME_PROJECTS}:/var/www/projects/"
      - "${VOLUME_DOMAINS}:/var/www/domains/"
      - "${VOLUME_TOOLS}:/var/www/tools/"

  # php71:
  #   build:
  #     context: ./docker/container/php/php71/
  #     dockerfile: Dockerfile
  #   container_name: php71
  #   dns: "${DNS_IP}"
  #   environment:
  #     VIRTUAL_HOST: "${PHP71_VIRTUAL_HOSTS}"
  #     XDEBUG_CONFIG: "remote_host=${HOST_IPS[1]}"
  #   image: flower7c3/php:7.1-apache
  #   links:
  #     - mysql55
  #     - mysql56
  #     - elastic1
  #   networks:
  #     webserver:
  #       ipv4_address: ${PHP71_DOCKER_NETWORK_IP}
  #   restart: always
  #   volumes:
  #     - "~/.ssh/:/root/.ssh/"
  #     - "${VOLUME_WWW_INDEX}:/var/www/html/"
  #     - "${VOLUME_PROJECTS}:/var/www/projects/"
  #     - "${VOLUME_DOMAINS}:/var/www/domains/"
  #     - "${VOLUME_TOOLS}:/var/www/tools/"

  yarn:
    build:
      context: ./docker/container/yarn/
      dockerfile: Dockerfile
    container_name: yarn
    dns: "${DNS_IP}"
    ports:
      - "${YARN_BRIDGED_PORT}:8080"
    image: flower7c3/yarn
    networks:
      webserver:
        ipv4_address: ${YARN_DOCKER_NETWORK_IP}
    restart: 'no'
    tty: true
    volumes:
      - "${VOLUME_PROJECTS}:/var/www/projects/"
      - "${VOLUME_DOMAINS}:/var/www/domains/"
      - "${VOLUME_TOOLS}:/var/www/tools/"

  node4:
    build:
      context: ./docker/container/node/node4/
      dockerfile: Dockerfile
    container_name: node4
    dns: "${DNS_IP}"
    ports:
      - "${NODE4_BRIDGED_PORT}:8080"
    image: flower7c3/node:4
    networks:
      webserver:
        ipv4_address: ${NODE4_DOCKER_NETWORK_IP}
    restart: 'no'
    tty: true
    volumes:
      - "${VOLUME_PROJECTS}:/var/www/projects/"
      - "${VOLUME_DOMAINS}:/var/www/domains/"
      - "${VOLUME_TOOLS}:/var/www/tools/"

  node5:
    build:
      context: ./docker/container/node/node5/
      dockerfile: Dockerfile
    container_name: node5
    dns: "${DNS_IP}"
    ports:
      - "${NODE5_BRIDGED_PORT}:8080"
    image: flower7c3/node:5
    networks:
      webserver:
        ipv4_address: ${NODE5_DOCKER_NETWORK_IP}
    restart: 'no'
    tty: true
    volumes:
      - "${VOLUME_PROJECTS}:/var/www/projects/"
      - "${VOLUME_DOMAINS}:/var/www/domains/"
      - "${VOLUME_TOOLS}:/var/www/tools/"

  node6:
    build:
      context: ./docker/container/node/node6/
      dockerfile: Dockerfile
    container_name: node6
    dns: "${DNS_IP}"
    ports:
      - "${NODE6_BRIDGED_PORT}:8080"
    image: flower7c3/node:6
    networks:
      webserver:
        ipv4_address: ${NODE6_DOCKER_NETWORK_IP}
    restart: 'no'
    tty: true
    volumes:
      - "${VOLUME_PROJECTS}:/var/www/projects/"
      - "${VOLUME_DOMAINS}:/var/www/domains/"
      - "${VOLUME_TOOLS}:/var/www/tools/"

networks:

  webserver:
    driver: bridge
    driver_opts:
      name: compose_webserver
      # com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: 192.168.33.0/24
        gateway: 192.168.33.254
