version: "2"

options:
  compose-file-path: 'docker-compose.yml'
  verbose: true
  rsync_image: 'eugenmayer/rsync'
  unison_image: 'eugenmayer/unison'
  cli_mode: 'auto'
  max_attempt: 5
  project_root: 'pwd'

syncs:
  projects-sync:
    host_disk_mount_mode: 'cached'
    src: '${VOLUME_PROJECTS_SOURCE}'
    sync_strategy: '${DOCKER_SYNC_STRATEGY}'
    sync_userid: 33
    sync_excludes: ['.git', '.github', '.idea', '.gitignore', '.DS_Store']
    watch_excludes: ['.*/.git', '.*/node_modules', '.*/bower_components', '.*/sass-cache', '.*/.sass-cache', '.*/.sass-cache', '.coffee', '.gitignore']
    watch_args: '-v'  
  domains-sync:
    host_disk_mount_mode: 'cached'
    src: '${VOLUME_DOMAINS_SOURCE}'
    sync_strategy: '${DOCKER_SYNC_STRATEGY}'
    sync_userid: 33
    sync_excludes: ['.git', '.github', '.idea', '.gitignore', '.DS_Store']
    watch_excludes: ['.*/.git', '.*/node_modules', '.*/bower_components', '.*/sass-cache', '.*/.sass-cache', '.*/.sass-cache', '.coffee', '.gitignore']
    watch_args: '-v'  
