#!/usr/bin/env bash

MYSQL56_ROOT_PASSWORD=rootpasswd
MYSQL56_DOCKER_NETWORK_IP=192.168.33.156
MYSQL56_BRIDGED_PORT=3356

VOLUME_MYSQL56_LOCAL_PATH="${VOLUME_DATABASES_LOCAL_PATH}mysql/mysql56/data/"
VOLUME_MYSQL56_TARGET="/var/lib/mysql"
if [[ "$DOCKER_SYNC_STRATEGY" == "" ]]; then
    VOLUME_MYSQL56_TYPE="bind"
    VOLUME_MYSQL56_SOURCE="${VOLUME_MYSQL56_LOCAL_PATH}"
    VOLUME_MYSQL56_OPTIONS=""
    VOLUME_MYSQL56_DEFINITION=""
else
    VOLUME_MYSQL56_TYPE="volume"
    VOLUME_MYSQL56_SOURCE="mysql56-sync"
    VOLUME_MYSQL56_OPTIONS="volume:
              nocopy: true"
    VOLUME_MYSQL56_DEFINITION="${VOLUME_MYSQL56_SOURCE}:
        external: true"
fi
