  mysql56:
    build:
      context: ./docker/container/mysql/mysql56/
      dockerfile: Dockerfile
    container_name: mysql56
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL56_ROOT_PASSWORD}"
    expose:
      - 3306
    image: flower7c3/mysql:5.6
    networks:
      webserver:
        ipv4_address: ${MYSQL56_DOCKER_NETWORK_IP}
    ports:
      - "${MYSQL56_BRIDGED_PORT}:3306"
    restart: always
    volumes:
      - "${VOLUME_SSH}:/root/.ssh/"
      - "projects-sync:/var/www/projects/:nocopy"
      - "domains-sync:/var/www/domains/:nocopy"
      # - "${VOLUME_PROJECTS}:/var/www/projects/"
      # - "${VOLUME_DOMAINS}:/var/www/domains/"
      - "mysql56-sync:/var/lib/mysql/:nocopy"
      # - "${VOLUME_DATABASES}mysql/mysql56/data/:/var/lib/mysql"
      - "${VOLUME_TOOLS}:/var/www/bin/"

