
  php55:
    build:
      context: ./docker/container/php/php55/
      dockerfile: Dockerfile
    container_name: php55
    dns: "${DNS_IP}"
    environment:
      VIRTUAL_HOST: "${PHP55_VIRTUAL_HOSTS}"
      XDEBUG_CONFIG: "remote_host=${XDEBUG_HOST}"
    image: flower7c3/php:5.5-apache
    networks:
      webserver:
        ipv4_address: ${PHP55_DOCKER_NETWORK_IP}
    restart: always
    volumes:
      - "${VOLUME_SSH}:/root/.ssh/"
      - "${VOLUME_WWW_INDEX}:/var/www/html/"
      - "${VOLUME_PROJECTS}:/var/www/projects/"
      - "${VOLUME_DOMAINS}:/var/www/domains/"
      - "${VOLUME_TOOLS}:/var/www/bin/"