#!/usr/bin/env bash

ELASTICSEARCH1_DOCKER_NETWORK_IP=192.168.33.161
ELASTICSEARCH1_BRIDGED_PORT=9201

VOLUME_ELASTIC1_LOCAL_PATH="${VOLUME_DATABASES_LOCAL_PATH}elasticsearch/elasticsearch1/"
VOLUME_ELASTIC1_TARGET="/usr/share/elasticsearch/data/"
if [[ "$DOCKER_SYNC_STRATEGY" == "" ]]; then
    VOLUME_ELASTIC1_TYPE="bind"
    VOLUME_ELASTIC1_SOURCE="${VOLUME_ELASTIC1_LOCAL_PATH}"
    VOLUME_ELASTIC1_OPTIONS=""
    VOLUME_ELASTIC1_DEFINITION=""
else
    VOLUME_ELASTIC1_TYPE="volume"
    VOLUME_ELASTIC1_SOURCE="elasticsearch1-sync"
    VOLUME_ELASTIC1_OPTIONS="volume:
              nocopy: true"
    VOLUME_ELASTIC1_DEFINITION="${VOLUME_ELASTIC1_SOURCE}:
        external: true"
fi
