  elastic1:
    container_name: elastic1
    dns: "${DNS_IP}"
    image: elasticsearch:1
    networks:
      ${NETWORK_NAME}:
        # ipv4_address: ${ELASTICSEARCH1_DOCKER_NETWORK_IP}
    ports:
      - "${ELASTICSEARCH1_BRIDGED_PORT}:9200"
    restart: 'no'
    tty: true
    volumes:
      - type: bind
        source: "${VOLUME_SSH_SOURCE}"
        target: "${VOLUME_SSH_TARGET}"
      - type: bind
        source: "${VOLUME_TOOLS_LOCAL_PATH}"
        target: "${VOLUME_TOOLS_TARGET}"
      - type: "${VOLUME_PROJECTS_TYPE}"
        source: "${VOLUME_PROJECTS_SOURCE}"
        target: "${VOLUME_PROJECTS_TARGET}"
        ${VOLUME_PROJECTS_OPTIONS}
      - type: "${VOLUME_DOMAINS_TYPE}"
        source: "${VOLUME_DOMAINS_SOURCE}"
        target: "${VOLUME_DOMAINS_TARGET}"
        ${VOLUME_DOMAINS_OPTIONS}
      - type: "${VOLUME_ELASTIC1_TYPE}"
        source: "${VOLUME_ELASTIC1_LOCAL_PATH}"
        target: "${VOLUME_ELASTIC1_TARGET}"
        ${VOLUME_ELASTIC1_OPTIONS}
