

  elastic1:
    container_name: elastic1
    dns: "${DNS_IP}"
    image: elasticsearch:1
    networks:
      webserver:
        ipv4_address: ${ELASTICSEARCH1_DOCKER_NETWORK_IP}
    ports:
      - "${ELASTICSEARCH1_BRIDGED_PORT}:9200"
    restart: 'no'
    tty: true
    volumes:
      - "${VOLUME_SSH}:/root/.ssh/"
      - "${VOLUME_DATABASE}esdata/:/usr/share/elasticsearch/data/"
      - "${VOLUME_PROJECTS}:/var/www/projects/"
      - "${VOLUME_DOMAINS}:/var/www/domains/"
      - "${VOLUME_TOOLS}:/var/www/bin/"

