  elastic1:
    container_name: elastic1
    dns: "${DNS_IP}"
    image: elasticsearch:1
    networks:
      webserver:
        ipv4_address: ${ELASTICSEARCH1_DOCKER_NETWORK_IP}
    ports:
      - "${ELASTICSEARCH1_BRIDGED_PORT}:9200"
    restart: 'no'
    tty: true
    volumes:
      - "${VOLUME_SSH}:/root/.ssh/"
      - "elasticsearch1-sync:/usr/share/elasticsearch/data/:nocopy"
      # - "${VOLUME_DATABASES}elasticsearch/elasticsearch1/:/usr/share/elasticsearch/data/"
      - "projects-sync:/var/www/projects/:nocopy"
      - "domains-sync:/var/www/domains/:nocopy"
      # - "${VOLUME_PROJECTS}:/var/www/projects/"
      # - "${VOLUME_DOMAINS}:/var/www/domains/"
      - "${VOLUME_TOOLS}:/var/www/bin/"
