  node4:
    build:
      context: ./docker/container/node/node4/
      dockerfile: Dockerfile
    container_name: node4
    dns: "${DNS_IP}"
    expose:
      - 8080
    ports:
      - "${NODE4_BRIDGED_PORT}:8080"
    image: flower7c3/node:4
    networks:
      webserver:
        ipv4_address: ${NODE4_DOCKER_NETWORK_IP}
    restart: 'no'
    tty: true
    volumes:
      - "${VOLUME_SSH}:/root/.ssh/"
      - "projects-sync:/var/www/projects/:nocopy"
      - "domains-sync:/var/www/domains/:nocopy"
      # - "${VOLUME_PROJECTS}:/var/www/projects/"
      # - "${VOLUME_DOMAINS}:/var/www/domains/"
      - "${VOLUME_TOOLS}:/var/www/bin/"
