#!/usr/bin/env bash

ELASTICSEARCH5_DOCKER_NETWORK_IP=192.168.33.165
ELASTICSEARCH5_BRIDGED_PORT=9205

VOLUME_ELASTIC5_LOCAL_PATH="${VOLUME_DATABASES_LOCAL_PATH}elasticsearch/elasticsearch5/"
VOLUME_ELASTIC5_TARGET="/usr/share/elasticsearch/data/"
if [[ "$DOCKER_SYNC_STRATEGY" == "" ]]; then
    VOLUME_ELASTIC5_TYPE="bind"
    VOLUME_ELASTIC5_SOURCE="${VOLUME_ELASTIC5_LOCAL_PATH}"
    VOLUME_ELASTIC5_OPTIONS=""
    VOLUME_ELASTIC5_DEFINITION=""
else
    VOLUME_ELASTIC5_TYPE="volume"
    VOLUME_ELASTIC5_SOURCE="elasticsearch5-sync"
    VOLUME_ELASTIC5_OPTIONS="volume:
              nocopy: true"
    VOLUME_ELASTIC5_DEFINITION="${VOLUME_ELASTIC5_SOURCE}:
        external: true"
fi
