#!/usr/bin/env bash

REDIS3_DOCKER_NETWORK_IP=192.168.33.173
REDIS3_BRIDGED_PORT=6379

VOLUME_REDIS3_LOCAL_PATH="${VOLUME_DATABASES_LOCAL_PATH}mysql/redis3/data/"
VOLUME_REDIS3_TARGET="/data/"
if [[ "$DOCKER_SYNC_STRATEGY" == "" ]]; then
    VOLUME_REDIS3_TYPE="bind"
    VOLUME_REDIS3_SOURCE="${VOLUME_REDIS3_LOCAL_PATH}"
    VOLUME_REDIS3_OPTIONS=""
    VOLUME_REDIS3_DEFINITION=""
else
    VOLUME_REDIS3_TYPE="volume"
    VOLUME_REDIS3_SOURCE="redis3-sync"
    VOLUME_REDIS3_OPTIONS="volume:
              nocopy: true"
    VOLUME_REDIS3_DEFINITION="${VOLUME_REDIS3_SOURCE}:
        external: true"
fi
