  node5:
    build:
      context: ./docker/container/node/node5/
      dockerfile: Dockerfile
    container_name: node5
    dns: "${DNS_IP-8.8.8.8}"
    expose:
      - 8080
    ports:
      - "${NODE5_BRIDGED_PORT-9005}:8080"
    image: flower7c3/node:5
    networks:
      webserver:
        # ipv4_address: ${NODE5_DOCKER_NETWORK_IP}
    restart: 'no'
    tty: true
    volumes:
      - type: bind
        source: "${VOLUME_SSH_LOCAL_PATH}"
        target: "${VOLUME_SSH_TARGET}"
      - type: bind
        source: "${VOLUME_BASH_HISTORY_LOCAL_PATH}"
        target: "${VOLUME_BASH_HISTORY_TARGET}"
      - type: bind
        source: "${VOLUME_TOOLS_LOCAL_PATH}"
        target: "${VOLUME_TOOLS_TARGET}"
      - type: bind
        source: "${VOLUME_PROJECTS_LOCAL_PATH}"
        target: "${VOLUME_PROJECTS_TARGET}"
        volume:
          cached: true
      - type: bind
        source: "${VOLUME_DOMAINS_LOCAL_PATH}"
        target: "${VOLUME_DOMAINS_TARGET}"
        volume:
          cached: true
