  bundler:
    build:
      context: ./docker/container/node/bundler/
      dockerfile: Dockerfile
    container_name: bundler
    dns: "${DNS_IP-8.8.8.8}"
    ports:
      - "${NODE4B_BRIDGED_PORT}:8080"
    image: flower7c3/node:4-bundler
    networks:
      webserver:
    # restart: 'no'
    tty: true
    volumes:
      - type: bind
        source: "${VOLUME_SSH_LOCAL_PATH}"
        target: "${VOLUME_SSH_TARGET}"
      - type: bind
        source: "${VOLUME_BASH_HISTORY_LOCAL_PATH}"
        target: "${VOLUME_BASH_HISTORY_TARGET}"
      - type: bind
        source: "${VOLUME_TOOLS_LOCAL_PATH}"
        target: "${VOLUME_TOOLS_TARGET}"
      - type: bind
        source: "${VOLUME_PROJECTS_LOCAL_PATH}"
        target: "${VOLUME_PROJECTS_TARGET}"
        volume:
          cached: true
      - type: bind
        source: "${VOLUME_DOMAINS_LOCAL_PATH}"
        target: "${VOLUME_DOMAINS_TARGET}"
        volume:
          cached: true
