  bundler:
    build:
      context: ./docker/container/node/bundler/
      dockerfile: Dockerfile
    container_name: bundler
    dns: "${DNS_IP}"
    ports:
      - "${NODE4B_BRIDGED_PORT}:8080"
    image: flower7c3/node:4-bundler
    networks:
      webserver:
        ipv4_address: ${NODE4B_DOCKER_NETWORK_IP}
    restart: 'no'
    tty: true
    volumes:
      - "projects-sync:/var/www/projects/:nocopy"
      - "domains-sync:/var/www/domains/:nocopy"
      # - "${VOLUME_PROJECTS}:/var/www/projects/"
      # - "${VOLUME_DOMAINS}:/var/www/domains/"
      - "${VOLUME_TOOLS}:/var/www/bin/"
