  php56:
    build:
      context: ./docker/container/php/php56/
      dockerfile: Dockerfile
    container_name: php56
    environment:
      VIRTUAL_HOST: "${PHP56_VIRTUAL_HOSTS}"
      XDEBUG_CONFIG: "remote_host=${XDEBUG_HOST-192.168.0.1}"
    dns: "${DNS_IP-8.8.8.8}"
    image: flower7c3/php:5.6-apache
    networks:
      webserver:
    # restart: always
    volumes:
      - type: bind
        source: "${VOLUME_SSH_LOCAL_PATH}"
        target: "${VOLUME_SSH_TARGET}"
      - type: bind
        source: "${VOLUME_BASH_HISTORY_LOCAL_PATH}"
        target: "${VOLUME_BASH_HISTORY_TARGET}"
      - type: bind
        source: "${VOLUME_TOOLS_LOCAL_PATH}"
        target: "${VOLUME_TOOLS_TARGET}"
      - type: bind
        source: "${VOLUME_PROJECTS_LOCAL_PATH}"
        target: "${VOLUME_PROJECTS_TARGET}"
        volume:
          cached: true
      - type: bind
        source: "${VOLUME_DOMAINS_LOCAL_PATH}"
        target: "${VOLUME_DOMAINS_TARGET}"
        volume:
          cached: true
