
  php56:
    build:
      context: ./docker/container/php/php56/
      dockerfile: Dockerfile
    container_name: php56
    environment:
      VIRTUAL_HOST: "${PHP56_VIRTUAL_HOSTS}"
      XDEBUG_CONFIG: "remote_host=${HOST_IPS[1]}"
    dns: "${DNS_IP}"
    image: flower7c3/php:5.6-apache
    networks:
      webserver:
        ipv4_address: ${PHP56_DOCKER_NETWORK_IP}
    restart: always
    volumes:
      - "${VOLUME_SSH}:/root/.ssh/"
      - "${VOLUME_WWW_INDEX}:/var/www/html/"
      - "${VOLUME_PROJECTS}:/var/www/projects/"
      - "${VOLUME_DOMAINS}:/var/www/domains/"
      - "${VOLUME_TOOLS}:/var/www/bin/"