  php71:
    build:
      context: ./docker/container/php/php71/
      dockerfile: Dockerfile
    container_name: php71
    dns: "${DNS_IP}"
    environment:
      VIRTUAL_HOST: "${PHP71_VIRTUAL_HOSTS}"
      XDEBUG_CONFIG: "remote_host=${XDEBUG_HOST}"
    image: flower7c3/php:7.1-apache
    networks:
      ${NETWORK_NAME}:
        # ipv4_address: ${PHP71_DOCKER_NETWORK_IP}
    restart: always
    volumes:
      - type: bind
        source: "${VOLUME_SSH_SOURCE}"
        target: "${VOLUME_SSH_TARGET}"
      - type: bind
        source: "${VOLUME_TOOLS_LOCAL_PATH}"
        target: "${VOLUME_TOOLS_TARGET}"
      - type: "${VOLUME_PROJECTS_TYPE}"
        source: "${VOLUME_PROJECTS_SOURCE}"
        target: "${VOLUME_PROJECTS_TARGET}"
        ${VOLUME_PROJECTS_OPTIONS}
      - type: "${VOLUME_DOMAINS_TYPE}"
        source: "${VOLUME_DOMAINS_SOURCE}"
        target: "${VOLUME_DOMAINS_TARGET}"
        ${VOLUME_DOMAINS_OPTIONS}
